version: '3'

tasks:
  default:
    desc: Show the available tasks
    cmds:
      - task --list --sort alphanumeric

  setup:
    desc: "Setup development environment"
    silent: true
    status:
      - rustup target list --installed | grep -q x86_64-apple-darwin
      - rustup target list --installed | grep -q aarch64-apple-darwin
    cmds:
      - rustup target add x86_64-apple-darwin
      - rustup target add aarch64-apple-darwin

  test:
    desc: "Run all tests"
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo test --all-features

  build:
    desc: Build the project in release mode
    cmds:
      - task: build:release

  build:*:
    desc: Build the Rust binary with the requested Cargo profile
    vars:
      TARGET: '{{index .MATCH 0}}'
    cmds:
      - cargo build --profile {{.TARGET}}

  install:
    desc: "Install binary locally via cargo install --path ."
    cmds:
      - task: uninstall
      - cargo install --path .
  install:brew:
    desc: Install via Homebrew tap
    cmds:
      - task: uninstall
      - brew install mikegarde/tap/dotenv-cli
  install:npm:
    desc: Local development setup
    cmds:
      - task: uninstall
      - npm install
      - task: build:release
      - npm install -g
  install:npm:repo:
    desc: Local development setup
    cmds:
      - task: uninstall
      - npm install -g @mikegarde/dotenv-cli@0.6.1
  uninstall:
    desc: "Uninstall all local installations of dotenv-cli (cargo, npm, brew)"
    internal: true
    cmds:
      - cargo uninstall dotenv-cli || true
      - cargo uninstall --path . || true
      - brew uninstall mikegarde/tap/dotenv-cli || true
      - npm uninstall -g @mikegarde/dotenv-cli || true
      - npm uninstall -g || true

  is-branch-safe:
    desc: Check if the current branch is main
    vars:
      BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
    cmds:
      - |
        if [ "{{.BRANCH}}" != "main" ] && [ "{{.BRANCH}}" != "develop" ]; then
          echo "Not on main or develop branch"
          exit 1
        fi

  release:*:
    desc: "Bump version, build & upload macOS assets, then dispatch GitHub Actions for Linux/Windows & Homebrew tap update. Usage: task release:[patch|minor|major|X.Y.Z]"
    silent: true
    preconditions:
      - sh: task is-branch-safe
        msg: "Not on main or develop branch"
    vars:
      STEP: '{{index .MATCH 0}}'
    cmds:
      - devops/release/1-bump-version.sh {{.STEP}}
      - task test
      - devops/release/2-tag-version.sh
      - devops/release/release.sh --macos

  release:finalize:
    desc: Publish the draft release if all expected assets have been uploaded
    cmds:
      - devops/release/finalize-release.sh

  publish:
    desc: Publish a release to npmjs and GitHub Packages
    preconditions:
      - task is-branch-safe
    cmds:
      - task: publish:npm
      - task: publish:github

  publish:npm:
    desc: Publish a release to npmjs
    preconditions:
      - task is-branch-safe
    cmds:
      - npm run publish:npm

  publish:github:
    desc: Publish a release to GitHub Packages
    preconditions:
      - task is-branch-safe
    cmds:
      - npm run publish:github
